//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvgPlotting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvgPlotting.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;function&gt;(-{0,1}[a-z0-9\.]+\([^\)]*\)|-{0,1}[a-z0-9\.]+))).
        /// </summary>
        internal static string rxCssTransformFunction {
            get {
                return ResourceManager.GetString("rxCssTransformFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;paramValue&gt;-{0,1}[a-z0-9\.]+)).
        /// </summary>
        internal static string rxCssTransformFunctionParams {
            get {
                return ResourceManager.GetString("rxCssTransformFunctionParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;functionName&gt;-{0,1}[a-z0-9\.]+)\((?&lt;functionParams&gt;[^\)]*)\)).
        /// </summary>
        internal static string rxCssTransformFunctionParts {
            get {
                return ResourceManager.GetString("rxCssTransformFunctionParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?i:[^0-9a-z-\.]*(?&lt;param&gt;([a-z]+|-{0,1}\d+(\.\d+){0,1}(e-{0,1}\d+){0,1}))[^0-9a-z-\.]*)).
        /// </summary>
        internal static string rxFindSvgTransformParams {
            get {
                return ResourceManager.GetString("rxFindSvgTransformParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;value&gt;-{0,1}\d+(\.\d+){0,1}).
        /// </summary>
        internal static string rxNumericalFloat {
            get {
                return ResourceManager.GetString("rxNumericalFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;value&gt;-{0,1}\d+).
        /// </summary>
        internal static string rxNumericalInt {
            get {
                return ResourceManager.GetString("rxNumericalInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;numeric&gt;-{0,1}\d+(\.\d+){0,1}(e-{0,1}\d+){0,1})(?&lt;suffix&gt;[a-z\%]*)).
        /// </summary>
        internal static string rxNumericWithSuffix {
            get {
                return ResourceManager.GetString("rxNumericWithSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;x&gt;-{0,1}\d+(\.\d+){0,1})\s*,\s*(?&lt;y&gt;-{0,1}\d+(\.\d+){0,1})).
        /// </summary>
        internal static string rxXYCoordinatePair {
            get {
                return ResourceManager.GetString("rxXYCoordinatePair", resourceCulture);
            }
        }
    }
}
